retention_data_raw = [
    {
        "cohort": "Sep 15, 2023",
        "initial_customers": 2157,
        "weeks": [
            {"value": 100.0, "count": 2157},
            {"value": 69.2, "count": 1492},
            {"value": 49.3, "count": 1063},
            {"value": 44.6, "count": 962},
            {"value": 28.8, "count": 621},
            {"value": 23.9, "count": 515},
            {"value": 19.3, "count": 416},
            {"value": 12.6, "count": 271},
            {"value": 9.6, "count": 207},
            {"value": 8.2, "count": 176},
        ],
    },
    {
        "cohort": "Sep 22, 2023",
        "initial_customers": 2584,
        "weeks": [
            {"value": 100.0, "count": 2584},
            {"value": 62.2, "count": 1607},
            {"value": 51.9, "count": 1341},
            {"value": 46.4, "count": 1198},
            {"value": 29.1, "count": 751},
            {"value": 29.4, "count": 759},
            {"value": 18.5, "count": 478},
            {"value": 15.5, "count": 400},
            {"value": 15.8, "count": 408},
            {"value": None, "count": None},
        ],
    },
    {
        "cohort": "Sep 29, 2023",
        "initial_customers": 2873,
        "weeks": [
            {"value": 100.0, "count": 2873},
            {"value": 63.5, "count": 1824},
            {"value": 54.9, "count": 1577},
            {"value": 46.3, "count": 1330},
            {"value": 32.2, "count": 925},
            {"value": 27.5, "count": 790},
            {"value": 26.1, "count": 749},
            {"value": 15.4, "count": 442},
            {"value": None, "count": None},
            {"value": None, "count": None},
        ],
    },
    {
        "cohort": "Oct 6, 2023",
        "initial_customers": 2882,
        "weeks": [
            {"value": 100.0, "count": 2882},
            {"value": 61.8, "count": 1781},
            {"value": 55.0, "count": 1585},
            {"value": 39.6, "count": 1141},
            {"value": 32.4, "count": 933},
            {"value": 22.1, "count": 636},
            {"value": 19.4, "count": 559},
            {"value": None, "count": None},
            {"value": None, "count": None},
            {"value": None, "count": None},
        ],
    },
    {
        "cohort": "Oct 13, 2023",
        "initial_customers": 2925,
        "weeks": [
            {"value": 100.0, "count": 2925},
            {"value": 65.6, "count": 1918},
            {"value": 56.7, "count": 1658},
            {"value": 45.2, "count": 1322},
            {"value": 32.2, "count": 941},
            {"value": 28.0, "count": 819},
            {"value": None, "count": None},
            {"value": None, "count": None},
            {"value": None, "count": None},
            {"value": None, "count": None},
        ],
    },
    {
        "cohort": "Oct 20, 2023",
        "initial_customers": 2066,
        "weeks": [
            {"value": 100.0, "count": 2066},
            {"value": 67.9, "count": 1402},
            {"value": 55.4, "count": 1144},
            {"value": 37.6, "count": 776},
            {"value": 29.7, "count": 613},
            {"value": None, "count": None},
            {"value": None, "count": None},
            {"value": None, "count": None},
            {"value": None, "count": None},
            {"value": None, "count": None},
        ],
    },
    {
        "cohort": "Oct 27, 2023",
        "initial_customers": 2302,
        "weeks": [
            {"value": 100.0, "count": 2302},
            {"value": 64.5, "count": 1484},
            {"value": 48.8, "count": 1123},
            {"value": 46.1, "count": 1061},
            {"value": None, "count": None},
            {"value": None, "count": None},
            {"value": None, "count": None},
            {"value": None, "count": None},
            {"value": None, "count": None},
            {"value": None, "count": None},
        ],
    },
    {
        "cohort": "Nov 3, 2023",
        "initial_customers": 2361,
        "weeks": [
            {"value": 100.0, "count": 2361},
            {"value": 66.9, "count": 1579},
            {"value": 51.0, "count": 1204},
            {"value": None, "count": None},
            {"value": None, "count": None},
            {"value": None, "count": None},
            {"value": None, "count": None},
            {"value": None, "count": None},
            {"value": None, "count": None},
            {"value": None, "count": None},
        ],
    },
    {
        "cohort": "Nov 10, 2023",
        "initial_customers": 2729,
        "weeks": [
            {"value": 100.0, "count": 2729},
            {"value": 69.9, "count": 1907},
            {"value": None, "count": None},
            {"value": None, "count": None},
            {"value": None, "count": None},
            {"value": None, "count": None},
            {"value": None, "count": None},
            {"value": None, "count": None},
            {"value": None, "count": None},
            {"value": None, "count": None},
        ],
    },
    {
        "cohort": "Nov 17, 2023",
        "initial_customers": 2905,
        "weeks": [
            {"value": 100.0, "count": 2905},
            {"value": None, "count": None},
            {"value": None, "count": None},
            {"value": None, "count": None},
            {"value": None, "count": None},
            {"value": None, "count": None},
            {"value": None, "count": None},
            {"value": None, "count": None},
            {"value": None, "count": None},
            {"value": None, "count": None},
        ],
    },
]
