fail_fast: true

repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.8.5
    hooks:
      - id: ruff-format
        args: ["."]
      - id: ruff
        args: ["--fix", "--exit-non-zero-on-fix"]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args: ["."]