name: Zip and Publish Subfolders
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: "Version tag for the artifacts"
        required: true
        type: string
jobs:
  zip-and-publish:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.list_zip_files.outputs.files }}
    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive
      - name: Create zip files for each subfolder
        run: |
          for dir in $(find . -mindepth 1 -maxdepth 1 -type d); do
            zip -r "${dir##*/}.zip" "$dir"
          done
      - name: List zip files
        id: list_zip_files
        run: |
          files=$(ls *.zip | jq -R . | jq -s . | tr -d '\n' | tr -d ' ')
          echo "files=$files" >> $GITHUB_OUTPUT
        shell: bash
      - name: Upload zip files as artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: zip-files
          path: "*.zip"

  upload-artifacts:
    needs: zip-and-publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Download zip files
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: zip-files
      - name: Upload release assets
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
        with:
          files: |
            *.zip
            templates.json
          tag_name: ${{ github.event.inputs.version || github.ref_name }}
