name: pre-commit

on:
  pull_request:
    branches: ['main']

jobs:
  pre-commit:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - run: |
          pip install pre-commit
          pre-commit run --all-files
