name: Publish Templates Prod
on:
  workflow_dispatch:
jobs:
  zip-and-publish:
    runs-on: ubuntu-latest
    environment: Reflex Build Dev
    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Upload all files in subfolders to R2
        env:
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          R2_BUCKET: ${{ secrets.R2_BUCKET }}
          R2_ENDPOINT: ${{ secrets.R2_ENDPOINT }}
        run: |
          pip install boto3
          python scripts/upload.py
      - name: Read templates.json
        id: templates_json
        run: |
          content=$(cat templates.json | jq -c .)
          echo "templates_json=$content" >> $GITHUB_OUTPUT
      - name: Trigger workflow in Flexgen repo
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: reflex-dev/flexgen
          event-type: trigger-from-publish
          client-payload: |
            {
              "message": "Templates published!",
              "environment": "Reflex Build Dev",
              "ref": "${{ github.ref }}",
              "run_id": "${{ github.run_id }}",
              "templates_json": ${{ steps.templates_json.outputs.templates_json }}
            }